import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth/config';
import { getDb } from '@/lib/db/config';
import { getSchemaContext } from '@/lib/mastra/schema-store';
import { executeNlQueryPipeline, buildSqlGenerationPrompt } from '@/lib/mastra/nl-query-pipeline';
import type { DataSource } from '@/types/database';

export async function POST(request: NextRequest) {
  const requestId = crypto.randomUUID();
  console.log(`\n[NL-QUERY ${requestId}] NEW REQUEST - ${new Date().toISOString()}`);
  console.log(`[NL-QUERY ${requestId}] URL: ${request.url}`);

  try {
    const session = await auth();
    if (!session?.user) {
      console.log(`[NL-QUERY ${requestId}] UNAUTHORIZED - No session`);
      return NextResponse.json(
        { success: false, error: { code: 'UNAUTHORIZED', message: 'Not authenticated' } },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { query, data_source_id, generated_sql } = body;

    console.log(`[NL-QUERY ${requestId}] User: ${session.user.email} (${session.user.id})`);
    console.log(`[NL-QUERY ${requestId}] Query: "${query}"`);
    console.log(`[NL-QUERY ${requestId}] Data Source ID: ${data_source_id}`);
    console.log(`[NL-QUERY ${requestId}] Generated SQL: ${generated_sql ? `"${generated_sql}"` : '(none)'}`);

    if (!query || !data_source_id) {
      console.log(`[NL-QUERY ${requestId}] VALIDATION ERROR - Missing required fields`);
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'query and data_source_id are required' } },
        { status: 400 }
      );
    }

    // Fetch data source
    const db = getDb();
    const dataSource = await db<DataSource>('data_sources')
      .where('id', data_source_id)
      .where('is_active', true)
      .first();

    if (!dataSource) {
      console.log(`[NL-QUERY ${requestId}] NOT FOUND - Data source not found`);
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Data source not found or inactive' } },
        { status: 404 }
      );
    }

    console.log(`[NL-QUERY ${requestId}] Data Source: "${dataSource.name}" (${dataSource.client_type})`);

    // If SQL was already generated by the LLM (via CopilotKit), use it directly
    if (generated_sql) {
      console.log(`[NL-QUERY ${requestId}] Executing pre-generated SQL...`);
      const result = await executeNlQueryPipeline(
        query,
        generated_sql,
        session.user.id,
        dataSource
      );

      console.log(`[NL-QUERY ${requestId}] Execution result:`, {
        accessGranted: result.accessGranted,
        hasError: !!result.error,
        hasResults: !!result.queryResults,
        rowCount: result.queryResults?.totalRows || 0,
        duration: result.queryResults?.executionTimeMs || 0,
      });

      return NextResponse.json({ success: true, data: result });
    }

    // Otherwise, get schema context for prompt generation
    console.log(`[NL-QUERY ${requestId}] No SQL provided - fetching schema for prompt...`);
    const schemaContext = await getSchemaContext(dataSource);
    const prompt = buildSqlGenerationPrompt(query, schemaContext.schemaText, dataSource.client_type);

    console.log(`[NL-QUERY ${requestId}] Generated prompt length: ${prompt.length}`);
    console.log(`[NL-QUERY ${requestId}] Schema text length: ${schemaContext.schemaText.length}`);

    return NextResponse.json({
      success: true,
      data: {
        prompt,
        schemaText: schemaContext.schemaText,
        dataSourceName: dataSource.name,
        dialect: dataSource.client_type,
      },
    });
  } catch (error) {
    console.error(`[NL-QUERY ${requestId}] ERROR:`, error);
    console.error(`[NL-QUERY ${requestId}] Error stack:`, error instanceof Error ? error.stack : 'No stack');
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: error instanceof Error ? error.message : 'Unknown error' } },
      { status: 500 }
    );
  }
}
