import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth/config';
import { getDb } from '@/lib/db/config';
import { getSchemaContext } from '@/lib/mastra/schema-store';
import { executeNlQueryPipeline, buildSqlGenerationPrompt } from '@/lib/mastra/nl-query-pipeline';
import type { DataSource } from '@/types/database';

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json(
        { success: false, error: { code: 'UNAUTHORIZED', message: 'Not authenticated' } },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { query, data_source_id, generated_sql } = body;

    if (!query || !data_source_id) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'query and data_source_id are required' } },
        { status: 400 }
      );
    }

    // Fetch data source
    const db = getDb();
    const dataSource = await db<DataSource>('data_sources')
      .where('id', data_source_id)
      .where('is_active', true)
      .first();

    if (!dataSource) {
      return NextResponse.json(
        { success: false, error: { code: 'NOT_FOUND', message: 'Data source not found or inactive' } },
        { status: 404 }
      );
    }

    // If SQL was already generated by the LLM (via CopilotKit), use it directly
    if (generated_sql) {
      const result = await executeNlQueryPipeline(
        query,
        generated_sql,
        session.user.id,
        dataSource
      );

      return NextResponse.json({ success: true, data: result });
    }

    // Otherwise, get schema context for prompt generation
    const schemaContext = await getSchemaContext(dataSource);
    const prompt = buildSqlGenerationPrompt(query, schemaContext.schemaText, dataSource.client_type);

    return NextResponse.json({
      success: true,
      data: {
        prompt,
        schemaText: schemaContext.schemaText,
        dataSourceName: dataSource.name,
        dialect: dataSource.client_type,
      },
    });
  } catch (error) {
    console.error('NL query execution error:', error);
    return NextResponse.json(
      { success: false, error: { code: 'INTERNAL_ERROR', message: error instanceof Error ? error.message : 'Unknown error' } },
      { status: 500 }
    );
  }
}
